# Setup
title:               Nombre Apellido
url:                 https://git.miren.bz/
author:
  name:              Nombre Apellido
  

## ^^ Añade tu personalización en la parte superior de este archivo ^^ ##
## == NO TOCAR A PARTIR DE AQUÍ == ##

tagline:             'Portafolio PWEB'
description:         'Portafolio de trabajo individual para la asignatura Proyectos para la web'
baseurl:             'lanyon'
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

date_format: "%-d %B %Y"
timezone: "Europe/Madrid"
