# Configuración
title:               Nombre Apellido
url:                 https://DeustoPWEB2020.github.io
author:
  name:              Nombre Apellido

# Si quieres cambiar el tema (colores) de tu portafolio, hazlo añadiendo 

# Si quieres crear una página estática con contenido, que aparezca
# enlazada en el menú lateral, duplica el archivo pagina.md y modifica
# el nombre del archivo y el título. 


## ^^ Añade tu personalización en la parte superior de este archivo ^^ ##
## == NO TOCAR A PARTIR DE AQUÍ == ##

tagline:             'Portafolio PWEB'
description:         'Portafolio de trabajo individual para la asignatura Proyectos para la web'
baseurl:             '/portafolio-plantilla'
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars

date_format: "%-d %B %Y"
timezone: "Europe/Madrid"
