# Setup
title:               Nombre Apellido
tagline:             'Portafolio PWEB'
description:         'Portafolio de trabajo individual para la asignatura Proyectos para la web'
url:                 https://git.miren.bz/lanyon/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nombre Apellido
  


## ^^ Añade tu personalización en la parte superior de este archivo ^^ ##
## == NO TOCAR A PARTIR DE AQUÍ == ##

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
